import Link from 'next/link';
import {StatsNav} from '@/components/stats-nav';
import {getStatsHistory,getModelHealth,getRefreshHealth,excludedRaceCount} from '@/lib/stats-data';
import {gridBands,driverStats,discoverPatterns,pct} from '@/lib/stats-analysis';
export const dynamic='force-dynamic';
export default async function HomePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const p=await searchParams;
  const series=typeof p.series==='string'?p.series:'all',season=typeof p.season==='string'?p.season:'all',track=typeof p.track==='string'?p.track:'all';
  const all=getStatsHistory();
  const rows=all.filter(r=>(series==='all'||r.series===series)&&(season==='all'||r.date.startsWith(season))&&(track==='all'||String(r.trackId)===track));
  const winners=rows.filter(r=>r.finish===1).sort((a,b)=>b.date.localeCompare(a.date)||b.raceId-a.raceId);
  const known=winners.filter(r=>r.start!==null),last10=winners.slice(0,10),lastKnown=last10.filter(r=>r.start!==null);
  const bands=gridBands(rows),drivers=driverStats(rows),patterns=discoverPatterns(rows,all),models=getModelHealth(),refresh=getRefreshHealth();
  const tracks=[...new Map(all.map(r=>[r.trackId,r.trackName])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));
  return <><StatsNav/><main className="mx-auto max-w-7xl space-y-9 px-5 py-8 sm:py-12">
    <section className="grid gap-6 lg:grid-cols-[1.2fr_1fr]">
      <div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Dirt late model intelligence</p><h1 className="mt-3 font-display text-4xl font-black tracking-tight sm:text-6xl">Find the story<br/>in the results.</h1><p className="mt-5 max-w-xl text-muted-strong">Who’s moving forward? Where do winners start? Explore the evidence, then take a closer look at the patterns worth watching.</p></div>
      <Link href="/preview/world-100" className="panel-raised flex flex-col justify-between border-accent/40 p-7 transition-colors hover:border-accent"><span className="text-xs font-bold uppercase tracking-widest text-accent">Race notebook · September 10–12, 2026</span><div><h2 className="mt-5 font-display text-3xl font-extrabold">56th World 100</h2><p className="mt-2 text-muted-strong">Twin 25 prelims. Eldora form. Baltes carryover. The questions to follow all weekend.</p></div><span className="mt-6 text-sm font-bold">Open the race preview ↗</span></Link>
    </section>
    <form className="panel flex flex-wrap items-end gap-4 p-5" action="/">
      <label className="flex min-w-44 flex-1 flex-col gap-2 text-xs font-bold text-muted-strong">Series<select name="series" defaultValue={series} className="rounded border border-border bg-surface-raised p-3 text-sm text-foreground"><option value="all">All late models</option>{[...new Set(all.map(r=>r.series))].sort().map(s=><option key={s}>{s}</option>)}</select></label>
      <label className="flex min-w-32 flex-col gap-2 text-xs font-bold text-muted-strong">Season<select name="season" defaultValue={season} className="rounded border border-border bg-surface-raised p-3 text-sm text-foreground"><option value="all">All seasons</option>{[...new Set(all.map(r=>r.date.slice(0,4)))].sort().reverse().map(s=><option key={s}>{s}</option>)}</select></label>
      <label className="flex min-w-44 flex-1 flex-col gap-2 text-xs font-bold text-muted-strong">Track<select name="track" defaultValue={track} className="rounded border border-border bg-surface-raised p-3 text-sm text-foreground"><option value="all">All tracks</option>{tracks.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
      <button className="rounded bg-accent px-6 py-3 text-sm font-bold text-white">Explore stats</button><Link href="/" className="p-3 text-sm text-muted">Reset</Link>
    </form>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4" aria-label="Coverage summary">{[
      [String(winners.length),'Recorded features'],[rows.length.toLocaleString(),'Feature result rows'],[pct(known.filter(r=>r.start!<=6).length,known.length),'Winners from positions 1–6'],[winners[0]?.date??'No results','Latest selected result']
    ].map(([value,label])=><div key={label} className="panel p-5"><p className="font-display text-2xl font-bold sm:text-3xl">{value}</p><p className="mt-2 text-xs text-muted">{label}</p></div>)}</section>
    <p className="-mt-4 text-xs leading-relaxed text-muted">Recorded history, not a complete season census. {known.length}/{winners.length} winners have a known starting position. {excludedRaceCount} audited conflicting races are excluded. Same-night features count separately. Filters apply to all sections below.</p>
    {!rows.length&&<p className="panel p-8">No eligible results match these filters. Try another season or track.</p>}
    <section className="grid gap-6 lg:grid-cols-2"><div className="panel p-6"><p className="text-xs uppercase tracking-widest text-accent">Starting position</p><h2 className="mt-2 text-2xl font-bold">Where the wins come from</h2><p className="mt-2 text-sm text-muted-strong">{lastKnown.filter(r=>r.start!>=6).length} of {lastKnown.length} known starts among the latest {last10.length} winners were sixth or farther back. {last10.length-lastKnown.length} unknown.</p>
      <div className="mt-6 space-y-5">{bands.map(b=><div key={b.label}><div className="flex justify-between text-sm"><span>Starting {b.label}</span><span className="font-semibold">{b.wins} wins · {b.rate} per starter</span></div><div className="mt-2 h-2 rounded bg-surface-hover"><div className="h-2 rounded bg-accent" style={{width:`${known.length?100*b.wins/known.length:0}%`}}/></div><p className="mt-1 text-xs text-muted">{b.starters} starts · 95% interval {b.interval}</p></div>)}</div><p className="mt-5 text-xs text-muted">Bars show the share of known-start winners. The rate uses all recorded starters in the band, not just winners. Descriptive intervals assume independent starts; repeat drivers and nights can widen uncertainty.</p></div>
      <div className="panel overflow-hidden"><div className="p-6"><p className="text-xs uppercase tracking-widest text-accent">Check the claim</p><h2 className="mt-2 text-2xl font-bold">The latest winners</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-raised text-xs text-muted"><tr><th className="px-6 py-3">Driver / event</th><th className="p-3">Date</th><th className="p-3">Start</th></tr></thead><tbody>{last10.map(r=><tr key={r.raceId} className="border-t border-border"><td className="px-6 py-3"><span className="font-semibold">{r.driverName}</span><a href={r.source?.startsWith('https://')?r.source:`/race/${r.raceId}`} className="mt-1 block max-w-72 truncate text-xs text-muted hover:text-foreground">{r.raceName} ↗</a></td><td className="whitespace-nowrap p-3 text-xs text-muted">{r.date}</td><td className="p-3 font-bold">{r.start??'—'}</td></tr>)}</tbody></table></div></div></section>
    <section><p className="text-xs font-bold uppercase tracking-widest text-accent">Beyond the finishing order</p><h2 className="mt-2 text-3xl font-bold">Patterns to investigate</h2><p className="mt-3 max-w-3xl text-sm text-muted-strong">Four defined questions, tested against the recorded history. These are exploratory associations, not proven betting edges. Driver strength, starting position, track and incomplete schedules can explain the differences. “Previous” means a strictly earlier race date.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{patterns.map(s=><article key={s.title} className="panel p-6"><h3 className="text-xl font-bold">{s.title}</h3><p className="mt-2 text-sm text-muted-strong">{s.detail}</p><div className="my-5 flex items-baseline gap-3"><strong className="font-display text-4xl">{s.rate}</strong><span className="text-xs text-muted">top-five rate vs {s.controlRate} without the signal</span></div><p className="text-xs text-muted">{s.success}/{s.n} signal starts · {s.controlSuccess}/{s.controlN} comparison starts · interval {s.interval}</p><p className="mt-3 text-xs text-muted-strong">{s.n<30||s.controlN<30?'Small sample — gather more evidence.':'Exploratory — not adjusted for driver, grid or track.'} Earlier lift: {s.early.lift===null?'insufficient sample':`${s.early.lift.toFixed(1)} points`}. 2025+ lift: {s.recent.lift===null?'insufficient sample':`${s.recent.lift.toFixed(1)} points`}.</p><details className="mt-4 text-xs"><summary className="cursor-pointer font-semibold">Show supporting examples</summary><ul className="mt-3 space-y-2 text-muted-strong">{s.evidence.map(r=><li key={`${r.raceId}-${r.driverId}`}><Link href={`/race/${r.raceId}`}>{r.date} · {r.driverName} · finished {r.finish} · {r.trackName}</Link></li>)}{!s.evidence.length&&<li>No qualifying examples in this selection.</li>}</ul></details></article>)}</div></section>
    <section className="panel overflow-hidden"><div className="p-6"><h2 className="text-2xl font-bold">Driver form</h2><p className="mt-2 text-sm text-muted">Sorted by wins, then top fives. Positive gain means positions made up. Last five shown newest first.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-raised text-xs text-muted"><tr>{['Driver','Starts','Wins','Top 5','Avg finish','Avg gain','Last five'].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{drivers.slice(0,25).map(d=><tr key={d.id} className="border-t border-border"><td className="whitespace-nowrap px-5 py-3 font-semibold"><Link href={`/admin/drivers/${d.id}`}>{d.name}</Link></td><td className="px-5">{d.starts}</td><td className="px-5">{d.wins}</td><td className="px-5">{d.top5}</td><td className="px-5">{d.average.toFixed(1)}</td><td className="px-5" title={`${d.gainSample} known starts`}>{d.gain===null?'—':`${d.gain>0?'+':''}${d.gain.toFixed(1)}`}</td><td className="whitespace-nowrap px-5 text-muted-strong">{d.last5.join(' · ')}</td></tr>)}</tbody></table></div></section>
    <section className="panel p-6"><h2 className="text-xl font-bold">Freshness & model status</h2><p className="mt-3 text-sm text-muted-strong">{refresh?`${refresh.ok?'Last refresh completed':'Refresh needs attention'}: ${refresh.lastRun}. ${refresh.message}`:'No automatic refresh has reported yet. The page uses the last stored results.'}</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{models.map(m=><div key={m.name} className="rounded border border-border p-3 text-xs"><p className="font-semibold">{m.name}</p><p className="mt-2 text-muted">History through {m.through??'not recorded'}</p><p className="mt-1 text-muted">Holdout top pick: {m.accuracy===null?'—':pct(m.accuracy,1)}</p></div>)}</div><p className="mt-4 text-xs text-muted">Evaluation: trained through 2024, tested on 2025+ before refitting the live model on all eligible data. Repeated holdout use and remaining data gaps limit the strength of these estimates.</p></section>
  </main><footer className="border-t border-border p-6 text-center text-xs text-muted">dirtIQ · Source-backed racing stats · Coverage matters as much as the headline.</footer></>;
}
