'use client';
import {useMemo,useState} from 'react';

export type WorldOddsRow={rank:number;driverId:number;name:string;car:string;probability:number;fairAmerican:string;decimal:number;chassis:string;engine:string};
function implied(line:string){const n=Number(line);if(!Number.isFinite(n)||n===0)return null;return n>0?100/(n+100):Math.abs(n)/(Math.abs(n)+100)}
function profit(line:string){const n=Number(line);if(!Number.isFinite(n)||n===0)return null;return n>0?n:10000/Math.abs(n)}
export function WorldOddsBoard({rows}:{rows:WorldOddsRow[]}){
 const [query,setQuery]=useState('');const [offers,setOffers]=useState<Record<number,string>>({});
 const shown=useMemo(()=>rows.filter(r=>`${r.name} ${r.car} ${r.chassis} ${r.engine}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 return <div className="panel overflow-hidden"><div className="flex flex-col gap-4 p-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-accent">Opening market · no vig</p><h2 className="mt-2 text-2xl font-bold">All registered drivers</h2><p className="mt-2 max-w-2xl text-sm text-muted-strong">Enter any sportsbook or private-market American price. DirtIQ calculates the gap against its fair probability; it does not place a wager.</p></div><label className="text-xs font-semibold text-muted">Search field<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Driver, chassis, engine" className="mt-2 block w-full min-w-64 rounded border border-border bg-background px-3 py-2 text-sm text-white"/></label></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-raised text-xs text-muted"><tr>{['#','Driver','Fair probability','Fair odds','Decimal','Offered odds','Edge / EV per $100','Equipment'].map(h=><th key={h} className="whitespace-nowrap px-4 py-3">{h}</th>)}</tr></thead><tbody>{shown.map(r=>{const offer=offers[r.driverId]??'';const book=implied(offer);const win=profit(offer);const edge=book===null?null:r.probability-book;const ev=win===null?null:r.probability*win-(1-r.probability)*100;return <tr key={r.driverId} className="border-t border-border"><td className="px-4 py-3 text-muted">{r.rank}</td><td className="whitespace-nowrap px-4 py-3 font-semibold">{r.name} <span className="text-xs text-muted">#{r.car}</span></td><td className="px-4 py-3 font-bold">{(r.probability*100).toFixed(1)}%</td><td className="px-4 py-3"><span className="rounded bg-accent px-2 py-1 font-black text-black">{r.fairAmerican}</span></td><td className="px-4 py-3 text-muted-strong">{r.decimal.toFixed(2)}</td><td className="px-4 py-3"><input aria-label={`Offered odds for ${r.name}`} value={offer} onChange={e=>setOffers({...offers,[r.driverId]:e.target.value})} placeholder="e.g. +900" className="w-24 rounded border border-border bg-background px-2 py-1.5 tabular-nums text-white"/></td><td className="whitespace-nowrap px-4 py-3">{edge===null?'—':<span className={edge>0?'text-green-400':'text-red-300'}>{edge>0?'+':''}{(edge*100).toFixed(1)} pts · {ev!>=0?'+':''}${ev!.toFixed(0)}</span>}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-muted">{r.chassis} · {r.engine}</td></tr>})}</tbody></table></div>{shown.length===0&&<p className="p-8 text-center text-sm text-muted">No drivers match that search.</p>}</div>
}
