import {readFileSync} from 'node:fs';
import path from 'node:path';
import {LivePolling} from '@/components/live-polling';
import {StatsNav} from '@/components/stats-nav';
import {getStatsHistory} from '@/lib/stats-data';
import {driverStats,pct} from '@/lib/stats-analysis';
import {getCachedMlPredictions} from '@/lib/ml-predictions';
export const dynamic='force-dynamic';
export const metadata={title:'World 100 race preview | dirtIQ'};
type Entry={driverId:number;name:string;car:string;chassis:string;engine:string};
const recentChampions=[
 [2025,'Ricky Thornton Jr.','first globe'],[2024,'Bobby Pierce','second globe'],[2023,"Hudson O’Neal",'first globe'],
 [2022,'Jonathan Davenport','fifth globe'],[2021,'Brandon Overton','first globe'],[2020,'Jonathan Davenport','fourth globe'],
 [2019,'Jonathan Davenport','third globe'],[2018,'Tim McCreadie','first globe'],[2017,'Jonathan Davenport','second globe'],
 [2016,'Bobby Pierce','first globe'],[2015,'Jonathan Davenport','first globe'],
] as const;
const modernWinnerStarts=[
 [2025,'Ricky Thornton Jr.',1,'https://www.eldoraspeedway.com/event_coverage/55th-world-100/'],
 [2024,'Bobby Pierce',3,'https://www.eldoraspeedway.com/event_coverage/54th-world-100/'],
 [2023,"Hudson O’Neal",2,'https://www.eldoraspeedway.com/event_coverage/53rd-world-100/'],
 [2022,'Jonathan Davenport',1,'https://www.eldoraspeedway.com/event_coverage/2022-world-100/'],
 [2021,'Brandon Overton',3,'https://www.eldoraspeedway.com/event_coverage/51st-world-100/'],
 [2020,'Jonathan Davenport',6,'https://www.eldoraspeedway.com/event_coverage/50th-world-100/'],
 [2019,'Jonathan Davenport',7,'https://www.eldoraspeedway.com/event_coverage/49th-annual-world-100-9-7-19/'],
 [2018,'Tim McCreadie',5,'https://www.eldoraspeedway.com/event_coverage/48th-annual-world-100/'],
 [2017,'Jonathan Davenport',3,'https://www.eldoraspeedway.com/event_coverage/47th-annual-world-100/'],
 [2016,'Bobby Pierce',22,'https://www.eldoraspeedway.com/event_coverage/46th-annual-world-100/'],
 [2015,'Jonathan Davenport',18,'https://www.eldoraspeedway.com/races/schedule/world-100/'],
] as const;
export default function WorldPreview(){
 const source=JSON.parse(readFileSync(path.join(process.cwd(),'public/data/world100.json'),'utf8')) as {source:string;checkedAt:string;entryListAsOf:string;poolRaceId:number;entries:Entry[]};
 const fullHistory=getStatsHistory();
 const posted=fullHistory.filter(r=>r.date>='2026-09-10'&&r.date<='2026-09-12'&&/world 100/i.test(r.raceName)&&r.finish<=3);
 const all=fullHistory.filter(r=>r.date<'2026-09-10');
 const eldora=all.filter(r=>r.trackName.toLowerCase().includes('eldora'));
 const history=new Map(driverStats(eldora).map(d=>[d.id,d]));
 const form=new Map(driverStats(all).map(d=>[d.id,d]));
 const predictions=getCachedMlPredictions(source.poolRaceId);
 const entrants=source.entries.map(e=>({...e,history:history.get(e.driverId),form:form.get(e.driverId),score:predictions.get(e.driverId)?.rawProbability??null,probability:predictions.get(e.driverId)?.probability??null})).sort((a,b)=>(b.score??-1)-(a.score??-1)||(b.history?.wins??0)-(a.history?.wins??0));
 const baltes=eldora.filter(r=>r.date==='2026-09-06'&&/baltes/i.test(r.raceName)&&r.finish<=5);
 const registeredIds=new Set(entrants.map(e=>e.driverId));
 const recentTopSix=modernWinnerStarts.slice(0,6).filter(([, ,start])=>start<=6).length;
 const modernDeep=modernWinnerStarts.filter(([, ,start])=>start>=7).length;
 const firstTimers=recentChampions.filter(([, ,note])=>note==='first globe').length;
 const modelTop=entrants.filter(e=>e.score!==null).slice(0,5);
 const prelimWinners=posted.filter(r=>r.finish===1&&/prelim|twin 25/i.test(r.raceName));
 const tally=(values:string[])=>[...new Map(values.map(v=>[v,values.filter(x=>x===v).length])).entries()].sort((a,b)=>b[1]-a[1]);
 const chassis=tally(entrants.map(e=>e.chassis.startsWith('Rocket')?'Rocket family':e.chassis||'Unreported'));
 const engines=tally(entrants.map(e=>e.engine.replace('Cornette','Cornett').replace('Scott Bailey Racing Engines','Scott Bailey')||'Unreported'));
 const davenport=entrants.find(e=>e.name==='Jonathan Davenport');
 const priced=entrants.filter(e=>e.probability!==null).slice(0,10);
 const american=(p:number)=>`+${Math.round(((1-p)/p)*100/10)*10}`;
 const moves=eldora.filter(r=>r.start!==null).map(r=>Math.abs(r.start!-r.finish)).sort((a,b)=>a-b);
 const medianMove=moves.length?moves[Math.floor(moves.length/2)]:null;
 const fivePlus=eldora.filter(r=>r.start!==null&&r.start-r.finish>=5).length;
 return <><StatsNav/><LivePolling enabled={true}/><main className="mx-auto max-w-7xl space-y-8 px-5 py-10">
 <section className="border-b border-border pb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">Race notebook · Eldora Speedway · September 10–12, 2026</p><h1 className="mt-4 font-display text-4xl font-black sm:text-6xl">The road to the globe.</h1><p className="mt-5 max-w-3xl text-lg text-muted-strong">World 100 starts with two 25-lap prelim features on Thursday. Watch how speed survives traffic, who gains places after qualifying, and whether recent Eldora form carries over to this field.</p><p className="mt-4 text-xs text-muted">Preview cutoff: September 10, before Thursday’s racing. Registration list dated {source.entryListAsOf}, checked {source.checkedAt.slice(0,10)}. <a className="underline" href={source.source}>Official event details and entry list ↗</a></p></section>
 <section className="grid gap-4 sm:grid-cols-3">{[
 ['THU · SEPT 10','Prelim night one','Twin 25s · $12,000 to win each','Hot laps 6:00 PM · Racing 7:30 PM ET'],
 ['FRI · SEPT 11','Prelim night two','Twin 25s · $12,000 to win each','Hot laps 6:00 PM · Racing 7:30 PM ET'],
 ['SAT · SEPT 12','World 100','Heats, B-features and the 100-lap final','Hot laps 6:30 PM · Racing 7:30 PM ET']
 ].map(([date,title,detail,time])=><article key={date} className="panel p-5"><p className="text-xs font-bold text-accent">{date}</p><h2 className="mt-3 text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-muted-strong">{detail}</p><p className="mt-4 text-xs text-muted">{time}</p></article>)}</section>
 <section><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">The globe by the numbers</p><h2 className="mt-2 font-display text-3xl font-black">History says a new name is plausible.</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
  <article className="panel p-5"><p className="font-display text-4xl font-black">{firstTimers} of 11</p><p className="mt-2 text-sm text-muted-strong">World 100s since 2015 produced a first-time winner.</p></article>
  <article className="panel p-5"><p className="font-display text-4xl font-black">5</p><p className="mt-2 text-sm text-muted-strong">Jonathan Davenport wins since 2015, the defining run of this era.</p></article>
  <article className="panel p-5"><p className="font-display text-4xl font-black">18th</p><p className="mt-2 text-sm text-muted-strong">Davenport's 2015 starting spot when he won his first globe.</p></article>
  <article className="panel p-5"><p className="font-display text-4xl font-black">5th?</p><p className="mt-2 text-sm text-muted-strong">Bobby Pierce can become the fifth Dream–World winner in one season.</p></article>
 </div><p className="mt-3 text-xs text-muted">First-time count uses Eldora's official 2015–2025 champions list. The sweep opportunity comes from Eldora's 2026 event reporting.</p></section>
 <section className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><article className="panel overflow-hidden"><div className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-accent">Recent globe room</p><h2 className="mt-2 text-2xl font-bold">Past World 100 winners</h2></div><div className="grid grid-cols-1 border-t border-border sm:grid-cols-2">{recentChampions.map(([year,name,note])=><div key={year} className="flex items-center justify-between gap-3 border-b border-border px-5 py-3 sm:odd:border-r"><span><b>{year}</b> · {name}</span><span className="text-xs text-muted">{note}</span></div>)}</div><a href="https://www.eldoraspeedway.com/world-100-driver-history/" className="block p-5 text-sm font-semibold text-accent">Explore Eldora's complete history ↗</a></article>
 <article className="panel p-6"><p className="text-xs font-bold uppercase tracking-widest text-accent">Early model board</p><h2 className="mt-2 text-2xl font-bold">Five drivers the model wants watched</h2>{modelTop.length?<ol className="mt-5 space-y-4">{modelTop.map((e,i)=><li key={e.driverId} className="flex items-center justify-between border-b border-border pb-3"><span><b className="mr-3 text-muted">{i+1}</b>{e.name} <span className="text-xs text-muted">#{e.car}</span></span><span className="text-xs text-muted">{e.history?.wins??0} Eldora wins</span></li>)}</ol>:<p className="mt-4 text-sm text-muted">Model scoring is waiting for the next refresh.</p>}<p className="mt-4 text-xs text-muted">This ranks the registration pool using pre-weekend form. It is not a win probability; groups, qualifying and prelim results will materially change the Saturday picture.</p></article></section>
 <section className="grid gap-6 lg:grid-cols-2"><article className="panel p-6"><p className="text-xs uppercase tracking-widest text-accent">Test the talking point</p><h2 className="mt-3 text-2xl font-bold">How close to the front must the winner start?</h2><div className="mt-5 grid grid-cols-2 gap-4"><div><p className="font-display text-4xl font-black">{recentTopSix} / 6</p><p className="mt-2 text-sm text-muted-strong">Last six editions won from sixth or better.</p></div><div><p className="font-display text-4xl font-black">{modernDeep} / 11</p><p className="mt-2 text-sm text-muted-strong">Since 2015 won from seventh or deeper.</p></div></div><p className="mt-4 text-sm text-muted"><b>Wording matters:</b> “sixth or better” means starting positions 1–6. It does not mean sixth or farther back. The recent streak is 100%; across all 11 modern editions shown, {pct(modernDeep,modernWinnerStarts.length)} came from seventh or deeper.</p><ul className="mt-4 grid gap-2 text-sm sm:grid-cols-2">{modernWinnerStarts.map(([year,name,start,url])=><li key={year}><a className="text-muted-strong hover:text-white" href={url}>{year} · {name} · start {start} ↗</a></li>)}</ul></article>
 <article className="panel p-6"><p className="text-xs uppercase tracking-widest text-accent">Recent track evidence</p><h2 className="mt-3 text-2xl font-bold">Baltes form to follow</h2><p className="mt-3 text-sm text-muted-strong">The September 6 twin features offer fresh Eldora evidence. Different fields and track conditions mean this is a watchlist, not proof of a World 100 advantage.</p><ul className="mt-5 space-y-3">{baltes.filter(r=>registeredIds.has(r.driverId)).map(r=><li key={`${r.raceId}-${r.driverId}`} className="flex justify-between gap-4 border-b border-border pb-2 text-sm"><span>{r.driverName}</span><span className="text-muted">{r.start} → {r.finish} · {r.raceName.endsWith('A')?'A':'B'}</span></li>)}</ul><p className="mt-4 text-xs text-muted">Registered drivers who finished top five in a Baltes feature. Arrows show starting and finishing position.</p></article></section>
 <section className="panel p-6"><p className="text-xs font-bold uppercase tracking-widest text-accent">Prelim winner signal</p><h2 className="mt-2 text-2xl font-bold">Can Thursday and Friday speed convert?</h2>{prelimWinners.length?<div className="mt-5 grid gap-4 sm:grid-cols-2">{prelimWinners.map(r=><article key={r.raceId} className="rounded border border-border p-4"><p className="text-xs text-muted">{r.raceName}</p><p className="mt-2 text-xl font-bold">{r.driverName}</p><p className="mt-1 text-sm text-muted-strong">Started {r.start??'unknown'}{r.start?` · gained ${r.start-r.finish} positions`:''}</p></article>)}</div>:<p className="mt-4 text-sm text-muted-strong">Awaiting the first verified Twin 25 winner. No winner is inferred from timing or an incomplete box score.</p>}<div className="mt-6 grid gap-3 text-sm sm:grid-cols-3"><div className="rounded bg-surface-raised p-4"><b>Conversion</b><p className="mt-1 text-muted">Did a prelim winner also win or podium Saturday?</p></div><div className="rounded bg-surface-raised p-4"><b>Traffic score</b><p className="mt-1 text-muted">Starting spot, finish and positions gained for every prelim winner.</p></div><div className="rounded bg-surface-raised p-4"><b>Model movement</b><p className="mt-1 text-muted">Compare the pre-weekend rank with the post-prelim race-night model.</p></div></div><p className="mt-4 text-xs text-muted">A historical prelim-to-World conversion rate will appear after the older Twin 25 results are fully verified. Until then, DirtIQ will not manufacture a percentage from incomplete history.</p></section>
 <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><article className="panel p-6"><p className="text-xs font-bold uppercase tracking-widest text-accent">Pre-prelim fair market</p><h2 className="mt-2 text-2xl font-bold">World 100 outright model prices</h2><p className="mt-3 text-sm text-muted-strong">No-vig prices across all 106 registrations before groups, qualifying or prelim results. These are DirtIQ estimates, not sportsbook offers.</p><ol className="mt-5 grid gap-x-8 gap-y-3 sm:grid-cols-2">{priced.map((e,i)=><li key={e.driverId} className="flex justify-between border-b border-border pb-2 text-sm"><span><b className="mr-2 text-muted">{i+1}</b>{e.name}</span><span><b>{american(e.probability!)}</b> <span className="text-xs text-muted">{pct(e.probability!*100,100)}</span></span></li>)}</ol><p className="mt-4 text-xs text-muted">Use these as a baseline for movement after each session. They include no house margin and should not be read as a guarantee that every registration starts Saturday.</p></article><article className="panel p-6"><p className="text-xs font-bold uppercase tracking-widest text-accent">Rain-delay read</p><h2 className="mt-2 text-2xl font-bold">Wet now; passing depends on the rework.</h2><p className="mt-3 text-sm text-muted-strong">Rossburg weather was reporting rain around 72°F on Thursday. Friday is forecast mostly sunny and humid; Saturday partly sunny, warm and humid.</p><div className="mt-5 grid grid-cols-2 gap-4"><div><p className="font-display text-3xl font-black">{medianMove??'—'}</p><p className="text-xs text-muted">Median positions changed in {moves.length} retained Eldora starts</p></div><div><p className="font-display text-3xl font-black">{pct(fivePlus,moves.length)}</p><p className="text-xs text-muted">Gained five or more positions</p></div></div><p className="mt-5 text-sm text-muted-strong">A wet, freshly worked surface can begin fast and narrow, making qualifying and the initial launch more valuable. Passing can improve if traffic opens a second groove; repeated rework can also reset that development. The database's old “Tacky” labels were defaults, so they cannot support an honest wet-versus-dry correlation yet.</p><a className="mt-4 inline-block text-xs font-semibold text-accent" href="https://www.eldoraspeedway.com/livetiming/">Eldora live timing ↗</a></article></section>
 <section className="panel p-6"><h2 className="text-2xl font-bold">Weekend result watch</h2><p className="mt-3 text-sm text-muted-strong">Official results are checked every 15 minutes by the data refresh. This page refreshes every 30 seconds.</p>{posted.length?<ul className="mt-4 space-y-2 text-sm">{posted.map(r=><li key={`${r.raceId}-${r.driverId}`}>{r.raceName} · P{r.finish} {r.driverName} · started {r.start??'unknown'}</li>)}</ul>:<p className="mt-4 text-sm text-muted">Awaiting verified Thursday–Saturday feature results. An unpublished or unrecognized box score stays pending.</p>}</section>
 <section><h2 className="text-2xl font-bold">Three things to watch tonight</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{[
 ['Qualifying versus race pace','Track the drivers who gain at least five places without a top-ten finish. A modest result can hide useful race pace; the stats page tests what follows that pattern.'],
 ['Performance within each group','Compare entrants within their assigned prelim field. An overall entry-list ranking is not a feature win probability. Recalculate after the groups and grids are confirmed.'],
 ['Repeatable progress','Look for drivers who move forward across sessions, not just the fastest single lap. Record the qualifying group and start position before judging the finishing order.']
 ].map(([h,t])=><article key={h} className="panel p-5"><h3 className="font-bold">{h}</h3><p className="mt-3 text-sm text-muted-strong">{t}</p></article>)}</div></section>
 <section><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">Equipment room</p><h2 className="mt-2 font-display text-3xl font-black">What is underneath the 106-car field?</h2><div className="mt-5 grid gap-5 lg:grid-cols-3"><article className="panel p-6"><h3 className="text-xl font-bold">Chassis</h3><ol className="mt-4 space-y-3">{chassis.slice(0,6).map(([name,count])=><li key={name} className="flex justify-between border-b border-border pb-2 text-sm"><span>{name}</span><b>{count} · {pct(count,entrants.length)}</b></li>)}</ol><p className="mt-3 text-xs text-muted">Rocket XR1, XR1.2 and XR2 are grouped into the Rocket family.</p></article><article className="panel p-6"><h3 className="text-xl font-bold">Engine builders</h3><ol className="mt-4 space-y-3">{engines.slice(0,7).map(([name,count])=><li key={name} className="flex justify-between border-b border-border pb-2 text-sm"><span>{name}</span><b>{count} · {pct(count,entrants.length)}</b></li>)}</ol><p className="mt-3 text-xs text-muted">Entry-list spellings are normalized. A choice between two builders remains undecided.</p></article><article className="panel p-6"><h3 className="text-xl font-bold">Davenport watch</h3><p className="mt-4 text-sm text-muted-strong">Official entry: <b>{davenport?.chassis??'unreported'}</b> chassis with <b>{davenport?.engine??'engine unreported'}</b>. He recently ran a Vic Hill engine at Port Royal, so the installed World 100 engine is a real pre-race variable.</p><div className="mt-5 rounded bg-surface-raised p-4"><b className="text-sm">Shock data</b><p className="mt-2 text-xs text-muted">Eldora does not publish shock brands on the entry list. Bilstein, Öhlins, Penske, Integra and others will be tracked only from a current team, manufacturer or verified inspection disclosure. Davenport's 2022 winning package publicly listed Bilstein; that does not prove his 2026 choice.</p></div></article></div><p className="mt-3 text-xs text-muted">These are field shares, not win rates. Historical chassis, engine and shock performance needs year-by-year equipment snapshots so today’s brands are not assigned backward to older races.</p></section>
 <section className="panel overflow-hidden"><div className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-accent">{entrants.length} official registrations</p><h2 className="mt-2 text-2xl font-bold">The field, with context</h2><p className="mt-3 max-w-3xl text-sm text-muted-strong">{predictions.size?'Ordered by the retrained early crown model across the registration pool.':'Ordered by recorded Eldora wins while model scoring is unavailable.'} This is a comparative ranking, not odds for either prelim. Entries are not confirmed feature starters. Historical form uses only recorded, retained races before September 10.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-raised text-xs text-muted"><tr>{['Rank','Driver','Eldora starts / wins','Eldora avg finish','Last five recorded','Chassis','Engine'].map(h=><th className="px-5 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{entrants.map((e,i)=><tr key={e.driverId} className="border-t border-border"><td className="px-5 py-3 text-muted">{i+1}</td><td className="whitespace-nowrap px-5 font-semibold">{e.name}<span className="ml-2 text-xs text-muted">#{e.car}</span></td><td className="px-5">{e.history?`${e.history.starts} / ${e.history.wins}`:'No retained history'}</td><td className="px-5">{e.history?.average.toFixed(1)??'—'}</td><td className="whitespace-nowrap px-5 text-muted-strong">{e.form?.last5.join(' · ')??'—'}</td><td className="px-5 text-xs text-muted">{e.chassis}</td><td className="px-5 text-xs text-muted">{e.engine}</td></tr>)}</tbody></table></div></section>
 <p className="text-xs text-muted">Model rankings and trends are limited by incomplete series coverage and the excluded conflict records. Timing and entries may change; consult <a className="underline" href={source.source}>Eldora’s official event page</a>. This notebook stays anchored to the pre-Thursday cutoff.</p>
 </main></>;
}
